SUBROUTINE PERCON
 USE BASIC
 USE MATRIX
 IMPLICIT NONE 
 INTEGER :: IK,JK,KK,N_BC
 INTEGER :: I,J,K
 INTEGER :: NK,NI,NJ
 REAL (KIND = 8) :: X
 
 DO IK = 1,FACE_TOT
 	FACE_COE(IK)%COE_L = 0.0; FACE_COE(IK)%COE_U = 0.0
 	IF (FACE_COE(IK)%POINT_BC.NE.1) THEN 
 		NK = FACE_COE(IK)%C_SIZE
 ! Incomplete Lower Part
 		FACE_COE(IK)%COE_L(1) = 1.0
 		DO JK = 2,FACE_COE(IK)%LU_T
 			N_BC = FACE_COE(IK)%C_INDEX(JK)
 			IF (FACE_COE(N_BC)%POINT_BC.NE.1) THEN 
 				X = FACE_COE(IK)%XYZ_P(JK)
 				DO KK = 2,JK-1
 					I = FACE_COE(IK)%C_INDEX(KK)
 					NI = FACE_COE(I)%C_SIZE
 					DO J = 1,NI
 						NJ = FACE_COE(I)%C_INDEX(J)
 						IF (NJ.EQ.FACE_COE(IK)%C_INDEX(JK)) THEN 
 							X = X-FACE_COE(IK)%COE_L(KK)*FACE_COE(I)%COE_U(J)
 						END IF
 					END DO
 				END DO
 				I = FACE_COE(IK)%C_INDEX(JK)
 				FACE_COE(IK)%COE_L(JK) = X/(FACE_COE(I)%COE_U(1))
 			END IF
 		END DO
 ! Incomplete Upper Part
 		X = FACE_COE(IK)%XYZ_P(1)
 		DO JK = 2,FACE_COE(IK)%LU_T
 			I = FACE_COE(IK)%C_INDEX(JK)
 			NI = FACE_COE(I)%C_SIZE
 			DO J = 1,NI
 				NJ = FACE_COE(I)%C_INDEX(J)
 				IF (NJ.EQ.FACE_COE(IK)%C_INDEX(1)) THEN 
 					X = X-FACE_COE(IK)%COE_L(JK)*FACE_COE(I)%COE_U(J)
 				END IF
 			END DO
 		END DO
 		FACE_COE(IK)%COE_U(1) = X/1.0
 		DO JK = FACE_COE(IK)%LU_T+1,NK
 			X = FACE_COE(IK)%XYZ_P(JK)
 			DO KK = 2,JK-1
 				I = FACE_COE(IK)%C_INDEX(KK)
 				NI = FACE_COE(I)%C_SIZE
 				DO J = 1,NI
 					NJ = FACE_COE(I)%C_INDEX(J)
 					IF (NJ.EQ.FACE_COE(IK)%C_INDEX(JK)) THEN 
 						X = X-FACE_COE(IK)%COE_L(KK)*FACE_COE(I)%COE_U(J)
 					END IF
 				END DO
 			END DO
 			I = FACE_COE(IK)%C_INDEX(JK)
 			FACE_COE(IK)%COE_U(JK) = X/1.0
 		END DO
 	END IF
 END DO
 
END SUBROUTINE PERCON


SUBROUTINE CG
 USE BASIC
 USE MATRIX
 IMPLICIT NONE 
 REAL (KIND = 8) :: PK(FACE_TOT),PKK(FACE_TOT),ZZK(FACE_TOT),RESO(FACE_TOT)
 REAL (KIND = 8) :: RH0,RH1,ALF,BET,X
 REAL (KIND = 8) :: RSM,RESK
 INTEGER :: IK,JK,KK,NS,IL,NK
 INTEGER :: INDEX_I
 
 !	OPEN (1220,FILE = 'COE_P.DAT')
 !	OPEN (1221,FILE = 'COE_L.DAT')
 !	OPEN (1222,FILE = 'COE_U.DAT')
 !	DO IK = 1,FACE_TOT
!		NK = FACE_COE(IK)%C_SIZE
!		WRITE (1220,'(I10,30F20.10)') FACE_COE(IK)%POINT_BC,FACE_COE(IK)%BZ,(FACE_COE(IK)%XYZ_P(JK),JK = 1,NK)
!		WRITE (1221,'(30F20.10)') (FACE_COE(IK)%COE_L(JK),JK = 1,NK)
!		WRITE (1222,'(30F20.10)') (FACE_COE(IK)%COE_U(JK),JK = 1,NK)
!	END DO
!	CLOSE (1220);  CLOSE (1221); CLOSE (1222) 
 
 
 
 ! Calculate the initial residual vector
 DO IK = 1,FACE_TOT
 	IF (FACE_COE(IK)%POINT_BC.NE.1) THEN 
 		FACE_COE(IK)%RES = FACE_COE(IK)%BZ
 		NK = FACE_COE(IK)%C_SIZE
 		DO JK = 1,NK
 			KK = FACE_COE(IK)%C_INDEX(JK)
 			FACE_COE(IK)%RES = FACE_COE(IK)%RES-FACE_COE(IK)%XYZ_P(JK)*FACE_COE(KK)%P
 		END DO
 	ELSE 
 		FACE_COE(IK)%RES = 0.0
 	END IF
 END DO
 
 ! Initialize working arrays and constants
 DO IK = 1,FACE_TOT
 	RESO(IK) = FACE_COE(IK)%RES
 	PK(IK) = 0.0; PKK(IK) = 0.0; ZZK(IK) = 0.0
 	FACE_COE(IK)%P1 = FACE_COE(IK)%P 
 END DO
 RH0 = 1.0; RH1 = 1.0; ALF = 1.0; BET = 1.0
 RSM = 1.0
 IL = 1
! OPEN (111,FILE = 'RESIDUAL.DAT')
 DO WHILE (RSM.GE.ERROX2.AND.IL.LE.300)
! Solve (M ZZK = RESO)
	DO IK = 1,FACE_TOT
		IF (FACE_COE(IK)%POINT_BC.NE.1) THEN 
			X = RESO(IK)
			NK = FACE_COE(IK)%C_SIZE
			DO JK = 2,NK
				KK = FACE_COE(IK)%C_INDEX(JK)
				X = X-FACE_COE(IK)%COE_L(JK)*ZZK(KK)
			END DO
			ZZK(IK) = X
		END IF
	END DO
	DO IK = FACE_TOT,1,-1
		IF (FACE_COE(IK)%POINT_BC.NE.1) THEN 
			X = ZZK(IK)
			NK = FACE_COE(IK)%C_SIZE
			DO JK = 2,NK
				KK = FACE_COE(IK)%C_INDEX(JK)
				X = X-FACE_COE(IK)%COE_U(JK)*ZZK(KK)
			END DO
			ZZK(IK) = X/FACE_COE(IK)%COE_U(1)
		END IF
	END DO

! Calculate RH1 = RESO*ZZK
	RH1 = 0.0
	DO IK = 1,FACE_TOT
		IF (FACE_COE(IK)%POINT_BC.NE.1) THEN 
			RH1 = RH1+RESO(IK)*ZZK(IK)
		END IF
	END DO
! Calculate PK = ZZK+BET*PK(I-1)
	IF (IL.EQ.1) THEN 
		DO IK = 1,FACE_TOT
			IF (FACE_COE(IK)%POINT_BC.NE.1) THEN 
				PK(IK) = ZZK(IK)
			END IF
		END DO
	ELSE 
		IF (ABS(RH0).GT.1.0E-10) THEN 
			BET = RH1/RH0
		ELSE 
			BET = 1.0
		END IF 
		DO IK = 1,FACE_TOT
			IF (FACE_COE(IK)%POINT_BC.NE.1) THEN 
				PK(IK) = ZZK(IK)+BET*PK(IK)
			END IF
		END DO	
	END IF
! Calculate PKK = A*PK
	DO IK = 1,FACE_TOT
		IF (FACE_COE(IK)%POINT_BC.NE.1) THEN 
			PKK(IK) = 0.0
			NK = FACE_COE(IK)%C_SIZE
			DO JK = 1,NK
				KK = FACE_COE(IK)%C_INDEX(JK)
				PKK(IK) = PKK(IK)+FACE_COE(IK)%XYZ_P(JK)*PK(KK)
			!	IF (IL.EQ.1.AND.IK.EQ.13) THEN 
			!		WRITE (111,'(I10,5F20.10)') JK,FACE_COE(IK)%XYZ_P(JK),PK(KK)
			!	END IF
			END DO
		END IF
	END DO
! Calculate PK*PKK
	ALF = 0.0
	DO IK = 1,FACE_TOT
		IF (FACE_COE(IK)%POINT_BC.NE.1) THEN 
		!	IF (IL.EQ.1) THEN 
		!		WRITE (111,'(I10,5F20.10)') IK,PK(IK),PKK(IK),ZZK(IK)
		!	END IF
			ALF = ALF+PK(IK)*PKK(IK)
		END IF
	END DO
! Calculate alpha = RH1/(PK*PKK)
	IF (ABS(ALF).GT.1.0E-10) THEN 
		ALF = RH1/ALF
	ELSE 
		ALF = 0.0
	END IF
! Update P = P_(I-1)+alpha*PK
! and RESO = RESO(I-1)-alpha*PKK
	DO IK = 1,FACE_TOT
		IF (FACE_COE(IK)%POINT_BC.NE.1) THEN 
			FACE_COE(IK)%P = FACE_COE(IK)%P+ALF*PK(IK)
			RESO(IK) = RESO(IK)-ALF*PKK(IK)
		END IF
	END DO
	
	RSM = 0.0; INDEX_I = 1
	DO IK = 1,FACE_TOT
	IF (FACE_COE(IK)%POINT_BC.NE.1) THEN 
		RESK = FACE_COE(IK)%BZ
		NK = FACE_COE(IK)%C_SIZE
		RESK = ABS(FACE_COE(IK)%P-FACE_COE(IK)%P1)
		IF (ABS(RESK).GT.RSM) THEN 
			RSM = ABS(RESK)
			INDEX_I = IK
		END IF
	END IF
	END DO
!	WRITE (*,*) 'CHECK',IL,RSM,INDEX_I,FACE_COE(INDEX_I)%P
	DO IK = 1,FACE_TOT
	IF (FACE_COE(IK)%POINT_BC.NE.1) THEN 
		FACE_COE(IK)%P1 = FACE_COE(IK)%P
	END IF
	END DO
	
	RH0 = RH1
	IL = IL+1
 END DO
! CLOSE (111)
 IF (RSM.GE.ERROX2) THEN 
	WRITE (*,*)'HARD',RSM,INDEX_I,FACE_COE(INDEX_I)%P,FACE_COE(INDEX_I)%POINT_BC
!	WRITE (*,*) 'P_FACE',FACE_COE(INDEX_I)%XC,FACE_COE(INDEX_I)%YC,FACE_COE(INDEX_I)%ZC
  END IF

END SUBROUTINE CG 
 



