MODULE POINT
 IMPLICIT NONE
 TYPE :: POINT_CONNECT
 	INTEGER :: C_SIZE,C_FLAG,C_NEW
 	INTEGER :: POINT_BC,BC_NUM
 	INTEGER, ALLOCATABLE :: C_INDEX(:)
 END TYPE POINT_CONNECT
 TYPE :: FACE_CAL_COR
 	REAL (KIND = 8) :: NODE_XYZ(2,2)
 END TYPE FACE_CAL_COR
END MODULE POINT 

SUBROUTINE INITIAL
 USE kd_tree
 USE BASIC
 USE POINT
 USE MATRIX 
 IMPLICIT NONE
 TYPE :: DY_POINT
 	INTEGER :: POINT_SIZE
 	INTEGER :: POINT_TYPE
 	INTEGER :: POINT_BC,BC_NUM
 	INTEGER, ALLOCATABLE :: POINT_INDEX(:)
 END TYPE DY_POINT
 INTEGER :: IK,JK,KK,I,J,K,NK
 INTEGER :: II,JJ,K1,K2
 INTEGER :: CON_FLAG
 INTEGER :: INITIAL_TYPE
 REAL (KIND = 8) :: X0,Y0,Z0,BZ0,NX,NY,X1,Y1,X2,Y2,H0,HR,ALPHA,A
 REAL (KIND = 8) :: NX0,NY0,NX1,NY1,LLX,LLY,LL,XK
 REAL (KIND = 8), ALLOCATABLE :: NODE_XYZ(:,:),XYZ_LOCAL(:,:),SHAPE_COE(:)
 REAL (KIND = 8), ALLOCATABLE :: OUTCOE(:)
 CHARACTER (LEN = 256) :: SM
 INTEGER :: NUM1,NUM2,NUM3,NUM_FLAG
 INTEGER :: ORD_FACE,ORD_TOTAL,FACE_NUM,XYZ_MAX
 TYPE (DY_POINT), ALLOCATABLE :: CELL_FACE(:),FACE(:),CELL(:)
 TYPE (POINT_CONNECT), ALLOCATABLE :: F_CON(:)
 INTEGER :: LOCAL(120)
 INTEGER :: ADJ_SIZE1,ADJ_SIZE2
 INTEGER :: F_START,F_END,F_FLAG,F_NN
 INTEGER, ALLOCATABLE :: FC_NEW(:)
 INTEGER, ALLOCATABLE :: F_NUM(:)
 REAL (KIND = 8) :: KTH1,ZMAX,ZMIN,KR,M_SUM
 CHARACTER (LEN = 256) :: PATH
 REAL (KIND = 8) :: KTH(2,2)
 TYPE (FACE_CAL_COR), ALLOCATABLE :: LINE_COR(:)
 REAL (KIND = 8) :: RNC_V,RNC_VX,RNC_VY
! For finding the nearest points for pumping wells 
 type (tree_master_record), Pointer :: tree_xy
 REAL :: query_xy(2)
 REAL, ALLOCATABLE :: R_DIST(:)
 REAL, ALLOCATABLE :: XYZ_LL(:,:)
 INTEGER, ALLOCATABLE :: R_POINTS(:)
 
 CALL getcwd(PATH)
 PATH = trim(PATH)//'/'
 NAME1 = trim(PATH)//'basic_input.dat'
 OPEN (1,FILE = trim(NAME1))
 READ (1,*) T_LIM,DT,DT_AMP,T_START ! Time Limits, time step, amplification, starting time
 READ (1,*) NCYC_OUT,NCYC_CHECK,OUT_TYPE 
 READ (1,*) UIT,SOIL_TOTAL ! UNIT controls soil MOisture Model; SOIL_TOTAL is the total number of soil types 
 READ (1,*) ERRO,ERROX2 ! Iteraction error tolerance
 READ (1,*) ZX ! Datum
 READ (1,*) WELL_NUM,HEAD_NUM,FLUX_NUM,RIVER_NUM,RAIN_NUM,DRAW_NUM 
 READ (1,*) INTER_CONTROL ! Bicgstab control (How many iteractions can be conducted)
 READ (1,*) PICARD_REL
 READ (1,*) K_SCHEME
 READ (1,*) NAME_FILE
 
 CLOSE (1)
 
 ALLOCATE (OUTPUT_VEC(OUT_TYPE))
 OUTPUT_VEC = 0.0
 IF (OUT_TYPE.NE.0) THEN 
 	NAME1 = trim(PATH)//'OUTPUT_TIME.DAT'
 	OPEN (1,FILE = trim(NAME1)) 
 	READ (1,*) (OUTPUT_VEC(IK),IK=1,OUT_TYPE)
 	CLOSE (1)
 END IF
  
 T = T_START
 
 
 OPEN (1,FILE = 'xyz.1.v.node')
 READ (1,*) NODE_TOT
 ALLOCATE (NODE_XYZ(NODE_TOT,2))
 DO IK = 1,NODE_TOT
 	READ (1,*) KK,NODE_XYZ(IK,1),NODE_XYZ(IK,2)
 END DO
 CLOSE (1)
 
 OPEN (1,FILE = 'face_vertex.dat')
 READ (1,*) FACE_TOT
 ALLOCATE (FACE(FACE_TOT))
 LOCAL = 0
 DO K = 1,FACE_TOT
 	FACE(K)%POINT_SIZE = 2
 	ALLOCATE (FACE(K)%POINT_INDEX(2))
 	READ (1,*) FACE(K)%POINT_INDEX(1),FACE(K)%POINT_INDEX(2),FACE(K)%POINT_BC,FACE(K)%BC_NUM
 END DO
 CLOSE (1)
 
 OPEN (1,FILE = 'cell_face.dat')
 READ (1,*) CELL_TOT
 ALLOCATE (CELL_FACE(CELL_TOT))
 LOCAL = 0
 DO K = 1,CELL_TOT
 	READ (1,*) NK,(LOCAL(IK),IK=1,NK)
 	CELL_FACE(K)%POINT_SIZE = NK
 	ALLOCATE (CELL_FACE(K)%POINT_INDEX(NK))
 	CELL_FACE(K)%POINT_TYPE = 0
 	DO IK = 1,NK
 		CELL_FACE(K)%POINT_INDEX(IK) = LOCAL(IK)
 		IF (LOCAL(IK).LT.0) THEN 
 			CELL_FACE(K)%POINT_TYPE = -1
 		END IF
 	END DO
 	LOCAL = 0
 END DO
 CLOSE (1)
 
 ALLOCATE (F_CON(FACE_TOT))
 DO K = 1,FACE_TOT
 	F_CON(K)%C_SIZE = 0
 	F_CON(K)%C_FLAG = 0; F_CON(K)%C_NEW = 0
 	F_CON(K)%POINT_BC = FACE(K)%POINT_BC
 	F_CON(K)%BC_NUM = FACE(K)%BC_NUM
 	ALLOCATE (F_CON(K)%C_INDEX(120))
 END DO
 
 DO K = 1,CELL_TOT
 	DO IK = 1,CELL_FACE(K)%POINT_SIZE
 		NUM1 = CELL_FACE(K)%POINT_INDEX(IK)
 		DO JK = 1,CELL_FACE(K)%POINT_SIZE
 			IF (IK.NE.JK) THEN 
 				NUM2 = CELL_FACE(K)%POINT_INDEX(JK)
 				CON_FLAG = 0
 				DO KK = 1,F_CON(NUM1)%C_SIZE
 					IF (F_CON(NUM1)%C_INDEX(KK).EQ.NUM2) THEN 
 						CON_FLAG = 1
 					END IF
 				END DO
 				IF (CON_FLAG.EQ.0) THEN 
 					F_CON(NUM1)%C_SIZE = F_CON(NUM1)%C_SIZE+1
 					NK = F_CON(NUM1)%C_SIZE
 					F_CON(NUM1)%C_INDEX(NK) = NUM2
 				END IF
 			END IF
 		END DO
 	END DO
 END DO

 F_FLAG = 0; NK = 1; II = 0
 DO WHILE (F_FLAG.EQ.0)
 	IF (F_CON(NK)%C_SIZE.GT.0) THEN 
 		F_FLAG = 1
 	END IF
 	NK = NK+1
 END DO
 DO IK = 1,FACE_TOT
 	IF (F_CON(IK)%C_SIZE.GT.II) THEN 
 		II = F_CON(IK)%C_SIZE
 	END IF
 END DO
 
 NK = NK-1
 WRITE (*,*) 'ORI',NK,FACE_TOT,II
 DO IK = 1,FACE_TOT
 	IF (F_CON(IK)%C_SIZE.GT.0) THEN 
 		IF (F_CON(IK)%C_SIZE.LT.F_CON(NK)%C_SIZE) THEN
 			NK = IK
 		END IF
 	END IF
 END DO
 
 WRITE (*,*) 'LEAST DEGREE',NK,F_CON(NK)%C_SIZE
 
 ALLOCATE (FC_NEW(FACE_TOT))
 FC_NEW = 0
 FC_NEW(1) = NK; F_CON(NK)%C_NEW = 1; F_CON(NK)%C_FLAG = 1
 F_FLAG = 0; F_START = 1; F_END = 1
 DO WHILE (F_FLAG.EQ.0)
 	NK = F_END+1
 	DO IK = F_START,F_END 
 		KK = FC_NEW(IK)
 		DO I = 1,F_CON(KK)%C_SIZE-1 
 			NUM1 = F_CON(KK)%C_INDEX(I)
 			ADJ_SIZE1 = 0
 			DO J = 1,F_CON(NUM1)%C_SIZE
 				II = F_CON(NUM1)%C_INDEX(J)
 				IF (F_CON(II)%C_FLAG.EQ.1) THEN 
 					ADJ_SIZE1 = ADJ_SIZE1+1
 				END IF
 			END DO
 			DO J = I+1,F_CON(KK)%C_SIZE
 				NUM2 = F_CON(KK)%C_INDEX(J)
 				ADJ_SIZE2 = 0
 				DO JJ = 1,F_CON(NUM2)%C_SIZE
 					II = F_CON(NUM2)%C_INDEX(JJ)
 					IF (F_CON(II)%C_FLAG.EQ.1) THEN 
 						ADJ_SIZE2 = ADJ_SIZE2+1
 					END IF 
 				END DO
 				IF (ADJ_SIZE2.LT.ADJ_SIZE1) THEN 
 					F_CON(KK)%C_INDEX(I) = NUM2
 					F_CON(KK)%C_INDEX(J) = NUM1
 					NUM1 = F_CON(KK)%C_INDEX(I)
 					NUM2 = F_CON(KK)%C_INDEX(J)
					II = ADJ_SIZE2
					ADJ_SIZE2 = ADJ_SIZE1
					ADJ_SIZE1 = II 					
 				END IF
 				IF (ADJ_SIZE2.EQ.ADJ_SIZE1) THEN 
 					IF (F_CON(NUM1)%C_SIZE.GT.F_CON(NUM2)%C_SIZE) THEN 
 						F_CON(KK)%C_INDEX(I) = NUM2
 						F_CON(KK)%C_INDEX(J) = NUM1
 						NUM1 = F_CON(KK)%C_INDEX(I)
 						NUM2 = F_CON(KK)%C_INDEX(J)
 					END IF
 				END IF
 			END DO
 		END DO
 		DO I = 1,F_CON(KK)%C_SIZE
 			K = F_CON(KK)%C_INDEX(I)
 			IF (F_CON(K)%C_FLAG.EQ.0) THEN 
 				FC_NEW(NK) = K
 				F_CON(K)%C_NEW = NK
 				F_CON(K)%C_FLAG = 1
 				NK = NK+1
 			END IF
 		END DO
 	END DO
 	F_START = F_END+1
 	F_END = NK-1
 	IF (F_END.LT.F_START) THEN 
 		F_FLAG = 1
 	END IF
 END DO
 
 WRITE (*,*) 'REORDERING',F_END
 
! Reverse this order 
 NK = 1
 DO K = 1,FACE_TOT
 	IF (F_CON(K)%C_SIZE.GT.0) THEN 
 		NK = F_CON(K)%C_NEW
 		F_CON(K)%C_NEW = F_END+1-NK
 		FC_NEW(F_END+1-NK) = K 
 	!	F_CON(K)%C_NEW = NK
 	!	FC_NEW(NK) = K
 	!	NK = NK+1
 	END IF
 END DO
 
 F_NN = 0
 DO K = 1,FACE_TOT
 	IF (F_CON(K)%C_SIZE.GT.0) THEN 
 		F_NN = F_NN+1
 	END IF
 END DO
 
 WRITE (*,*) 'REAL',F_NN
 
 F_NN = 0
 DO K = 1,FACE_TOT
 	IF (FC_NEW(K).GT.0) THEN 
 		F_NN = F_NN+1
 	END IF
 END DO
 
 WRITE (*,*) 'TEST',F_NN
 
 
 DO K = 1,FACE_TOT
 	IF (F_CON(K)%C_FLAG.EQ.0.AND.F_CON(K)%C_SIZE.GT.0) THEN 
 		WRITE (*,*) K,F_CON(K)%C_SIZE
 		DO I = 1,F_CON(K)%C_SIZE
 			KK = F_CON(K)%C_INDEX(I)
 			WRITE (*,*) F_CON(K)%C_INDEX(I),F_CON(KK)%C_NEW
 			WRITE (*,*) 'CHECK'
 			DO J = 1,F_CON(KK)%C_SIZE
 				WRITE (*,*) F_CON(KK)%C_INDEX(J)
 			END DO
 		END DO
 	END IF
 END DO
  
 OPEN (996,FILE = 'face_re.dat')
 OPEN (999,FILE = 'face_connect.dat')
 OPEN (997,FILE = 'cell_face_re.dat')
 WRITE (999,*) F_NN
 WRITE (996,*) F_NN
 WRITE (997,*) CELL_TOT
 DO IK = 1,FACE_TOT
 	NK = FC_NEW(IK)
 	IF (NK.NE.0) THEN 
 		KK = F_CON(NK)%C_SIZE
 		LOCAL = 0
 		DO I = 1,KK
 			J = F_CON(NK)%C_INDEX(I)
 			LOCAL(I) = F_CON(J)%C_NEW
 		END DO
 		WRITE (999,'(20I10)') KK,(LOCAL(I),I=1,KK)
 		KK = FACE(NK)%POINT_SIZE
 		LOCAL = 0
 		DO I = 1,KK
 			LOCAL(I) = FACE(NK)%POINT_INDEX(I)
 		END DO
 		WRITE (996,'(20I10)') F_CON(NK)%POINT_BC,F_CON(NK)%BC_NUM,KK,(LOCAL(I),I=1,KK)
 	END IF
 END DO
 
 DO IK = 1,CELL_TOT
 	NK = CELL_FACE(IK)%POINT_TYPE
 	KK = CELL_FACE(IK)%POINT_SIZE
 	LOCAL = 0
 	IF (NK.EQ.(-1)) THEN 
 		KK = 1
 		LOCAL(1) = -1
 	ELSE
 		DO I = 1,KK
 			J = CELL_FACE(IK)%POINT_INDEX(I)
 			LOCAL(I) = F_CON(J)%C_NEW
 		END DO
 	END IF
 	WRITE (997,'(20I10)') KK,(LOCAL(J),J=1,KK)
 END DO

 CLOSE (996)
 CLOSE (997)
 CLOSE (999)
 DEALLOCATE (FACE,CELL_FACE,F_CON)
 
 OPEN (1,FILE = 'face_re.dat')
 READ (1,*) FACE_TOT
 ALLOCATE (FACE(FACE_TOT))
 ALLOCATE (FACE_COE(FACE_TOT))
 LOCAL = 0
 DO K = 1,FACE_TOT
 	READ (1,*) FACE(K)%POINT_BC,FACE(K)%BC_NUM,NK,(LOCAL(IK),IK=1,NK)
 	FACE(K)%POINT_SIZE = NK
 	IF (NK.EQ.1.OR.NK.EQ.0) THEN 
 		FACE(K)%POINT_TYPE = -1
 	ELSE 
 		FACE(K)%POINT_TYPE = 0
 	END IF
 	ALLOCATE (FACE(K)%POINT_INDEX(NK))
 	DO IK = 1,NK
 		FACE(K)%POINT_INDEX(IK) = LOCAL(IK)
 	END DO
 	FACE_COE(K)%POINT_SIZE = FACE(K)%POINT_SIZE
 	ALLOCATE (FACE_COE(K)%NODE_XYZ(NK,2))
 	LOCAL = 0
 END DO
 CLOSE (1)
 
 OPEN (1,FILE = 'cell_face_re.dat')
 READ (1,*) CELL_TOT
 ALLOCATE (CELL_COE(CELL_TOT))
 LOCAL = 0
 DO K = 1,CELL_TOT
 	READ (1,*) NK,(LOCAL(IK),IK=1,NK)
 	CELL_COE(K)%POINT_SIZE = NK
 	ALLOCATE (CELL_COE(K)%POINT_INDEX(NK))
 	CELL_COE(K)%POINT_TYPE = 0
 	DO IK = 1,NK
 		CELL_COE(K)%POINT_INDEX(IK) = LOCAL(IK)
 		IF (LOCAL(IK).LT.0) THEN 
 			CELL_COE(K)%POINT_TYPE = -1
 		END IF
 	END DO
 	LOCAL = 0
 END DO
 CLOSE (1)
 
 OPEN (1,FILE = 'face_connect.dat')
 READ (1,*) FACE_TOT
 LOCAL = 0
 DO K = 1,FACE_TOT
 	READ (1,*) NK,(LOCAL(IK),IK=1,NK)
 	FACE_COE(K)%C_SIZE = NK+1
	ALLOCATE (FACE_COE(K)%C_INDEX(NK+1))
	FACE_COE(K)%POINT_BC = FACE(K)%POINT_BC
	FACE_COE(K)%BC_NUM = FACE(K)%BC_NUM
	FACE_COE(K)%C_INDEX(1) = K
	DO IK = 2,NK+1
		FACE_COE(K)%C_INDEX(IK) = LOCAL(IK-1)
	END DO 	
	LOCAL = 0
 END DO
 CLOSE (1)
 DO K = 1,FACE_TOT
 	NK = FACE_COE(K)%C_SIZE
 	ALLOCATE (FACE_COE(K)%XYZ_P(NK),FACE_COE(K)%COE_L(NK),FACE_COE(K)%COE_U(NK))
 	FACE_COE(K)%XYZ_P = 0.0; FACE_COE(K)%COE_L = 0.0; FACE_COE(K)%COE_U = 0.0
 	FACE_COE(K)%BZ = 0.0
 END DO
 
 ! Reorder the face neighbor number
 DO K = 1,FACE_TOT
 	NK = FACE_COE(K)%C_SIZE
 	DO JK = 2,NK-1
 		DO KK = JK+1,NK
 			IF (FACE_COE(K)%C_INDEX(JK).GT.FACE_COE(K)%C_INDEX(KK)) THEN 
 				I = FACE_COE(K)%C_INDEX(KK)
 				FACE_COE(K)%C_INDEX(KK) = FACE_COE(K)%C_INDEX(JK)
 				FACE_COE(K)%C_INDEX(JK) = I
 			END IF
 		END DO
 	END DO
 	FACE_COE(K)%LU_T = 0
 	JK = 2; KK = 0
 	DO WHILE (JK.LE.NK.AND.KK.EQ.0)
 		IF (FACE_COE(K)%C_INDEX(1).LT.FACE_COE(K)%C_INDEX(JK)) THEN 
 			KK = 1
 			FACE_COE(K)%LU_T = JK-1
 		END IF
 		JK = JK+1
 	END DO
 	IF (FACE_COE(K)%C_INDEX(1).LT.FACE_COE(K)%C_INDEX(2)) THEN 
 		FACE_COE(K)%LU_T = 1
 	END IF
 	IF (FACE_COE(K)%C_INDEX(1).GT.FACE_COE(K)%C_INDEX(NK)) THEN 
 		FACE_COE(K)%LU_T = NK
 	END IF
 END DO

! Compute the center of each face
 DO K = 1,FACE_TOT
 	IK = FACE(K)%POINT_INDEX(1)
 	JK = FACE(K)%POINT_INDEX(2)
 	X1 = NODE_XYZ(IK,1); Y1 = NODE_XYZ(IK,2)
 	X2 = NODE_XYZ(JK,1); Y2 = NODE_XYZ(JK,2)
 	FACE_COE(K)%NODE_XYZ(1,1) = X1; FACE_COE(K)%NODE_XYZ(1,2) = Y1
 	FACE_COE(K)%NODE_XYZ(2,1) = X2; FACE_COE(K)%NODE_XYZ(2,2) = Y2
 	FACE_COE(K)%XC = 0.5*(X1+X2)
 	FACE_COE(K)%YC = 0.5*(Y1+Y2)
 	FACE_COE(K)%CELL_IND = 0
 END DO
 
 ! Compute the center of each cell
 DO K = 1,CELL_TOT
 	NK = CELL_COE(K)%POINT_SIZE
 	X0 = 0.0; Y0 = 0.0
 	DO IK = 1,NK
 		KK = CELL_COE(K)%POINT_INDEX(IK)
 		X0 = X0+FACE_COE(KK)%XC
 		Y0 = Y0+FACE_COE(KK)%YC
 	END DO
 	X0 = X0/(NK*1.0); Y0 = Y0/(NK*1.0)
 	RNC_V = 0.0; RNC_VX = 0.0; RNC_VY = 0.0
 	DO IK = 1,NK
 		KK = CELL_COE(K)%POINT_INDEX(IK)
 		X1 = FACE_COE(KK)%NODE_XYZ(1,1); Y1 = FACE_COE(KK)%NODE_XYZ(1,2)
 		X2 = FACE_COE(KK)%NODE_XYZ(2,1); Y2 = FACE_COE(KK)%NODE_XYZ(2,2)
 		
 		NX = X2-X1; NY = Y2-Y1
 		LL = SQRT(NX*NX+NY*NY)
 		NX = NX/LL; NY = NY/LL
 		
 		IF (FACE_COE(KK)%CELL_IND(1).EQ.0) THEN 
 			FACE_COE(KK)%CELL_IND(1) = K
 		ELSE 
 			FACE_COE(KK)%CELL_IND(2) = K
 		END IF
 		
 		FACE_COE(KK)%AREA = LL
 		
 		NX1 = -NY; NY1 = NX
 		NX0 = 0.5*(X1+X2)-X0; NY0 = 0.5*(Y1+Y2)-Y0
 		
 		XK = NX0*NX1+NY0*NY1
 		IF (XK.LT.0.0) THEN 
 			NX1 = -NX1; NY1 = -NY1
 		END IF
 		FACE_COE(KK)%NX = NX1; FACE_COE(KK)%NY = NY1
 		
 		XK = NX1*X1+NY1*Y1
 		K1 = 0; K2 = 0
 		CALL LINE_CAL(X1,Y1,X2,Y2,K1,K2,LLX)
 		RNC_V = RNC_V+LLX*XK/(2.0+K1+K2)
 		K1 = 1; K2 = 0
 		CALL LINE_CAL(X1,Y1,X2,Y2,K1,K2,LLX)
 		RNC_VX = RNC_VX+LLX*XK/(2.0+K1+K2)
 		K1 = 0; K2 = 1
 		CALL LINE_CAL(X1,Y1,X2,Y2,K1,K2,LLX)
 		RNC_VY = RNC_VY+LLX*XK/(2.0+K1+K2)
 	END DO
 	CELL_COE(K)%X = RNC_VX/RNC_V; CELL_COE(K)%Y = RNC_VY/RNC_V
 	CELL_COE(K)%CELL_V = RNC_V
 	ALLOCATE (CELL_COE(K)%MCF(NK,NK),CELL_COE(K)%MCF1(NK,NK),CELL_COE(K)%PC(NK,NK))
 	ALLOCATE (CELL_COE(K)%RRNC(NK,2))
 	ALLOCATE (CELL_COE(K)%FA_COE(NK))
 END DO

 ! For boundary conditions
 ALLOCATE (QWELL(WELL_NUM),WELL_X(WELL_NUM),WELL_Y(WELL_NUM))
 ALLOCATE (WELL_COE(WELL_NUM))
! ALLOCATE (XYZ_WELL(WELL_NUM,3))
 ALLOCATE (H_INPUT(HEAD_NUM))
 ALLOCATE (QBX(FLUX_NUM),QBY(FLUX_NUM))
 ALLOCATE (RIVER_HEAD(RIVER_NUM),RIVER_BED(RIVER_NUM),RIVER_THICKNESS(RIVER_NUM))   !,RIVER_AREA(RIVER_NUM))
 ALLOCATE (Q_RAIN(RAIN_NUM))
! For the output
 ALLOCATE (DRAW_XYZ(DRAW_NUM))

! Read Soil properties file
 NAME1 = trim(PATH)//'soil.dat'    ! K_SS is the multiplier for the K_S
 OPEN (1,FILE = trim(NAME1))
 READ (1,*) INITIAL_TYPE
 DO K = 1,CELL_TOT
 	READ (1,*) CELL_COE(K)%HTH,CELL_COE(K)%SOIL_UNIT,CELL_COE(K)%K_SS
 END DO
 CLOSE (1)
 
 IF (INITIAL_TYPE.EQ.1) THEN ! MEANING THE INITIAL INPUT IS PRESSURE HEAD 
 	DO K = 1,CELL_TOT
 		CELL_COE(K)%HTH = CELL_COE(K)%HTH+CELL_COE(K)%Y
 	END DO
 END IF
 
 CALL SOIL_READ
 
 ! Assign the initial hydraulic head for face
 ALLOCATE (F_NUM(FACE_TOT))
 F_NUM = 0
 DO K = 1,FACE_TOT
 	FACE_COE(K)%P = 0.0
 END DO
 DO K = 1,CELL_TOT
 	IF (CELL_COE(K)%POINT_TYPE.NE.(-1)) THEN 
 		NK = CELL_COE(K)%POINT_SIZE
 		DO IK = 1,NK
 			I = CELL_COE(K)%POINT_INDEX(IK)
 			FACE_COE(I)%P = FACE_COE(I)%P+CELL_COE(K)%HTH*1.0
 			F_NUM(I) = F_NUM(I)+1
 		END DO
 	END IF
 END DO
 
 DO K = 1,FACE_TOT
 	FACE_COE(K)%P = FACE_COE(K)%P/(F_NUM(K)*1.0)
 END DO 
 
 DEALLOCATE (F_NUM)
 
 
 ! For node type: =0, interior node; =1, head bc; =2, flux bc
 ! =4, pumping/injection well; = 10 surface node; =11 zero depth bc; =12 critical depth bc
 ! For the surface node's nx and ny, they are read by alpha and m2 

! Read Output Coordinates
 NAME1 = trim(PATH)//'head_draw.dat'
 OPEN (1,FILE = trim(NAME1))
 DO I = 1,DRAW_NUM
 	READ (1,*) DRAW_XYZ(I)
 END DO
 CLOSE (1)
 
 CALL HEAD_READ 
 CALL FLUX_READ
 CALL WELL_READ
 CALL RIVER_READ
 CALL RAIN_READ
! OPEN (993,FILE = 'CENTER_CAL.DAT')
 ORD_TOTAL = 2; ORD_FACE = 2
 DO K = 1,CELL_TOT
 	DO IK = 1,2
 		DO JK = 1,2
 			KTH(IK,JK) = CELL_COE(K)%K_S(IK,JK)
 		END DO
 	END DO
 	NK = CELL_COE(K)%POINT_SIZE
 	ALLOCATE (LINE_COR(NK))
 	DO IK = 1,NK
 		KK = CELL_COE(K)%POINT_INDEX(IK)
 		LINE_COR(IK)%NODE_XYZ(1,1) = FACE_COE(KK)%NODE_XYZ(1,1)
 		LINE_COR(IK)%NODE_XYZ(1,2) = FACE_COE(KK)%NODE_XYZ(1,2)
 		LINE_COR(IK)%NODE_XYZ(2,1) = FACE_COE(KK)%NODE_XYZ(2,1)
 		LINE_COR(IK)%NODE_XYZ(2,2) = FACE_COE(KK)%NODE_XYZ(2,2)	
 	END DO
 	X0 = CELL_COE(K)%X; Y0 = CELL_COE(K)%Y
 	FACE_NUM = NK
 	CALL MFD_CAL(CELL_COE(K)%MCF1,CELL_COE(K)%PC,X0,Y0,FACE_NUM,LINE_COR,KTH,CELL_COE(K)%FA_COE, &
 		     CELL_COE(K)%RRNC)
	DEALLOCATE (LINE_COR)
 END DO
! CLOSE (993)

 
 ! Set up the head boundary 
 DO K = 1,FACE_TOT
 	IF (FACE_COE(K)%POINT_BC.EQ.1) THEN 
 		NK = FACE_COE(K)%BC_NUM
 		II = H_INPUT(NK)%DEG
 		JJ = 1
 		FACE_COE(K)%P = 0.0
 		IF (II.EQ.(-1)) THEN ! NATURAL LOG DISTRIBUTION
 			HR = H_INPUT(NK)%H_COE(1); A = H_INPUT(NK)%H_COE(2)
			ALPHA = H_INPUT(NK)%H_COE(3)
 			H0 = 1.0-EXP(ALPHA*HR)
 			FACE_COE(K)%P = FACE_COE(K)%YC+LOG(EXP(ALPHA*HR)+  &
 			H0/2.0*(1.0-COS(2.0*3.1415926*FACE_COE(K)%XC/A)))/ALPHA
 		!	FACE_COE(K)%P = FACE_COE(K)%YC+LOG(EXP(ALPHA*HR)+  &
 		!	H0*SIN(3.1415926*FACE_COE(K)%XC/A))/ALPHA
 		ELSE 
 			DO IK = 0,II
 				DO JK = 0,II-IK
 					FACE_COE(K)%P = ((FACE_COE(K)%XC)**IK)*((FACE_COE(K)%YC)**JK)*H_INPUT(NK)%H_COE(JJ)+ &
 							FACE_COE(K)%P
 					JJ = JJ+1
 				END DO
 			END DO
 		END IF
 	END IF
 !	IF (FACE_COE(K)%POINT_BC.EQ.2) THEN 
 !		NK = FACE_COE(K)%BC_NUM
 !		IF (ABS(QBX(NK)).GT.1.0E-4.OR.ABS(QBY(NK)).GT.1.0E-4) THEN 
 !			IF (FACE_COE(K)%P.LT.FACE_COE(K)%YC) THEN 
 !				FACE_COE(K)%P = FACE_COE(K)%YC
 !			END IF
 !		END IF
 !	END IF
 END DO
 
! DO K = 1,CELL_TOT
! 	NK = CELL_COE(K)%POINT_SIZE
! 	CELL_COE(K)%HTH = 0.0
! 	DO IK = 1,NK
! 		KK = CELL_COE(K)%POINT_INDEX(IK)
! 		CELL_COE(K)%HTH = CELL_COE(K)%HTH+FACE_COE(KK)%P
! 	END DO
! 	CELL_COE(K)%HTH = CELL_COE(K)%HTH/(NK*1.0)
! END DO 
 
  ! Initialize Soil Parameters
! OPEN (1,FILE = 'SOIL_CHECK.DAT')
 DO K = 1,CELL_TOT
 IF (CELL_COE(K)%POINT_TYPE.NE.(-1)) THEN
 	FACE_NUM = CELL_COE(K)%POINT_SIZE
 	KR = 0.0
 	M_SUM = FACE_NUM*1.0+1.0
 	DO IK = 1,FACE_NUM
 		KK = CELL_COE(K)%POINT_INDEX(IK)
 		IF (UIT.EQ.1) THEN 
 			call vg(CELL_COE(K)%MTH,KTH1,CELL_COE(K)%CTH,FACE_COE(KK)%P-FACE_COE(KK)%YC, &
 			CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%M2)
 		END IF
 		IF (UIT.EQ.2) THEN 
 			call Haverkamp(CELL_COE(K)%MTH,KTH1,CELL_COE(K)%CTH,FACE_COE(KK)%P-FACE_COE(KK)%YC,&
 			CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%A,CELL_COE(K)%M2,CELL_COE(K)%B)
 		END IF
 		IF (UIT.EQ.3) THEN 
 			call gardner(CELL_COE(K)%MTH,KTH1,CELL_COE(K)%CTH,FACE_COE(KK)%P-FACE_COE(KK)%YC,&
 			CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%M2)
 		END IF
 		IF (FACE_COE(KK)%POINT_BC.EQ.2) THEN 
 			KTH1 = 1.0
 		END IF
 		KR = KR+KTH1
 	END DO
 	IF (UIT.EQ.1) THEN 
 		call vg(CELL_COE(K)%MTH,KTH1,CELL_COE(K)%CTH,CELL_COE(K)%HTH-CELL_COE(K)%Y, &
 			CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%M2)
 	END IF
 	IF (UIT.EQ.2) THEN 
 		call Haverkamp(CELL_COE(K)%MTH,KTH1,CELL_COE(K)%CTH,CELL_COE(K)%HTH-CELL_COE(K)%Y,&
 		     CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%A,CELL_COE(K)%M2,CELL_COE(K)%B)
 	END IF
 	IF (UIT.EQ.3) THEN 
 		call gardner(CELL_COE(K)%MTH,KTH1,CELL_COE(K)%CTH,CELL_COE(K)%HTH-CELL_COE(K)%Y,&
 		     	     CELL_COE(K)%ALPHA,CELL_COE(K)%THETAS,CELL_COE(K)%THETAR,CELL_COE(K)%K_SS,CELL_COE(K)%M2)
 	END IF
 	KR = KR+KTH1
 !	CELL_COE(K)%KTH = CELL_COE(K)%K_SS*KR/(M_SUM*1.0)
 	CELL_COE(K)%KTH = CELL_COE(K)%K_SS*KTH1
 	CELL_COE(K)%HTHN = CELL_COE(K)%HTH
 	CELL_COE(K)%HTH1 = CELL_COE(K)%HTH
 	CELL_COE(K)%MTHN = CELL_COE(K)%MTH 
 END IF
 END DO 
! CLOSE (1)
 
 DO K = 1,FACE_TOT
 	FACE_COE(K)%P1 = FACE_COE(K)%P
 	FACE_COE(K)%PN = FACE_COE(K)%P
 	FACE_COE(K)%P_OLD = FACE_COE(K)%P
 END DO 
 
 ALLOCATE (NODE_CF(CELL_TOT+FACE_TOT))
 ALLOCATE (XYZ_LL(CELL_TOT+FACE_TOT,2))
 
 DO IK = 1,CELL_TOT
 	NODE_CF(IK)%T_FLAG = 0
 	NODE_CF(IK)%X = CELL_COE(IK)%X
 	NODE_CF(IK)%Y = CELL_COE(IK)%Y
 END DO
 
 DO IK = 1,FACE_TOT
 	NODE_CF(IK+CELL_TOT)%T_FLAG = 1
 	NODE_CF(IK+CELL_TOT)%X = FACE_COE(IK)%XC
 	NODE_CF(IK+CELL_TOT)%Y = FACE_COE(IK)%YC
 END DO
 
 DO IK = 1,CELL_TOT+FACE_TOT
 	XYZ_LL(IK,1) = NODE_CF(IK)%X
 	XYZ_LL(IK,2) = NODE_CF(IK)%Y
 END DO
 
 tree_xy => create_tree(XYZ_LL)
 DO IK = 1,WELL_NUM
 	query_xy(1) = WELL_X(IK); query_xy(2) = WELL_Y(IK)
 	NK = WELL_COE(IK)%LOCAL_NUM
 	ALLOCATE (R_DIST(NK))
 	ALLOCATE (R_POINTS(NK))
 	CALL n_nearest_to(tp=tree_xy, qv=query_xy, n=NK, indexes=R_POINTS, distances=R_DIST)
 	KK = 0
 	DO JK = 1,NK
 		IF (NODE_CF(R_POINTS(JK))%T_FLAG.EQ.0) THEN   ! = 0 FOR CELL NODE
 			KK = KK+1
 		END IF
 	END DO
 	WELL_COE(IK)%CELL_NUM = KK; WELL_COE(IK)%FACE_NUM = NK-KK
 	ALLOCATE (WELL_COE(IK)%WELL_CELL_INDEX(KK),WELL_COE(IK)%WELL_FACE_INDEX(NK-KK))
 	ALLOCATE (WELL_COE(IK)%CELL_COE(KK),WELL_COE(IK)%FACE_COE(NK-KK))
 	I = 0; J = 0
 	DO JK = 1,NK
 		IF (NODE_CF(R_POINTS(JK))%T_FLAG.EQ.0) THEN 
 			I = I+1
 			WELL_COE(IK)%WELL_CELL_INDEX(I) = R_POINTS(JK) 
 		ELSE 
 			J = J+1
 			WELL_COE(IK)%WELL_FACE_INDEX(J) = R_POINTS(JK)-CELL_TOT
 		END IF
 	END DO
 	FACE_NUM = WELL_COE(IK)%LOCAL_NUM
 	ALLOCATE (XYZ_LOCAL(FACE_NUM,2),SHAPE_COE(FACE_NUM))
 	DO JK = 1,WELL_COE(IK)%CELL_NUM  ! COEFFICIENTS FOR THE CELL NODES FIRST
 		II = WELL_COE(IK)%WELL_CELL_INDEX(JK)
 		XYZ_LOCAL(JK,1) = CELL_COE(II)%X
 		XYZ_LOCAL(JK,2) = CELL_COE(II)%Y
 	END DO	
 	NK = WELL_COE(IK)%CELL_NUM
 	DO JK = 1,WELL_COE(IK)%FACE_NUM
 		II = WELL_COE(IK)%WELL_FACE_INDEX(JK)
 		XYZ_LOCAL(JK+NK,1) = FACE_COE(II)%XC
 		XYZ_LOCAL(JK+NK,2) = FACE_COE(II)%YC
 	END DO
 	
 	X0 = WELL_X(IK); Y0 = WELL_Y(IK)
 	JK = FACE_NUM+3
 	CALL RBF_GAU(X0,Y0,FACE_NUM,JK,XYZ_LOCAL,SHAPE_COE)
 !	JK = 3
 !	CALL GMLS(X0,Y0,FACE_NUM,JK,XYZ_LOCAL,SHAPE_COE)

 	DO JK = 1,WELL_COE(IK)%CELL_NUM
 		WELL_COE(IK)%CELL_COE(JK) = SHAPE_COE(JK)
 	END DO
 	NK = WELL_COE(IK)%CELL_NUM
 	DO JK = 1,WELL_COE(IK)%FACE_NUM
 		WELL_COE(IK)%FACE_COE(JK) = SHAPE_COE(JK+NK)
 	END DO
 	DEALLOCATE (R_DIST,R_POINTS)
 	DEALLOCATE (XYZ_LOCAL,SHAPE_COE)
 END DO
 
 OPEN (99,FILE = 'WELL_INDEX.DAT')
 DO IK = 1,WELL_NUM
 	WRITE (99,*) 'WELL_NO = ',IK
 	WRITE (99,*) 'WELL COR = ',WELL_X(IK),WELL_Y(IK)
 	WRITE (99,*) 'CELL NUM = ',WELL_COE(IK)%CELL_NUM
 	NK = WELL_COE(IK)%CELL_NUM
 	DO JK = 1,NK
 		II = WELL_COE(IK)%WELL_CELL_INDEX(JK)
 		WRITE (99,*) CELL_COE(II)%X,CELL_COE(II)%Y,WELL_COE(IK)%CELL_COE(JK)
 	END DO	
 	WRITE (99,*) 'FACE NUM = ',WELL_COE(IK)%FACE_NUM
 	NK = WELL_COE(IK)%FACE_NUM
 	DO JK = 1,NK
 		II = WELL_COE(IK)%WELL_FACE_INDEX(JK)
 		WRITE (99,*) FACE_COE(II)%XC,FACE_COE(II)%YC,WELL_COE(IK)%FACE_COE(JK)
 	END DO	
 END DO
 CLOSE (99)

 END SUBROUTINE INITIAL
 
 
 
 
 
 
 
 
 
 
 
 
 
 
